# Generated by Django 4.0.2 on 2022-03-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordernumber_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_stock',
        ),
    ]
