# Generated by Django 4.0.2 on 2022-03-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_stock',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
