# Generated by Django 4.0.2 on 2022-03-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
