# Generated by Django 4.0.2 on 2022-03-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rate', models.IntegerField()),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('percentage', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
