# Generated by Django 4.0.2 on 2022-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0002_user_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_coupon',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
