# Generated by Django 4.0.2 on 2022-04-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0003_user_coupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_coupon',
            name='amount',
        ),
    ]
