# Generated by Django 4.0.2 on 2022-02-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('productname', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_in_stock', models.IntegerField(blank=True, default=0, help_text='Amount in stock')),
                ('offer_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
