# Generated by Django 4.0.2 on 2022-03-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_subcategory_product_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
