# Generated by Django 4.0.2 on 2022-04-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerstatus',
            field=models.BooleanField(null=True),
        ),
    ]
