# Generated by Django 4.0.2 on 2022-04-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_offerstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='price2',
        ),
    ]
