# Generated by Django 4.0.2 on 2022-04-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_discount_price_product_price2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerpercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
