# Generated by Django 4.0.2 on 2022-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_offerpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offerstatus',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
