# Generated by Django 4.0.2 on 2022-04-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_offerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offerstatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
